### ISSUE TITLE
[BUG] Exclusion rule is not applied

### ISSUE THREAD

**Issue by Elaws** [franciskafieh/obsidian-list-modified#119]
## Describe the bug

Desktop (Windows 11) and mobile (Android) are synced through SyncTrayzor/Syncthing. I would like to exclude temporary files created by syncthing (all of them have "~syncthing" in their name), but the exclusion rule I created (with "~syncthing") is not applied. I reinstalled the plugin with `isDesktopOnly` set to `true`, used the Clear tracked files but to no effect : temporary syncthing files are tracked by List Modified as soon as some modification is made on mobile. The bug happens only when modifications of a note are made on Obsidian mobile (and not on Obsidian desktop).

## Expected behaviour

Files with "~syncthing" in their name shouldn't be tracked.

### My setup

- Windows 11
- Obsidian 1.7.5
- List Modified v.3.2.0
- SyncTrayzor 1.28.0
- Android device with Obsidian and Syncthing app.

### Steps to reproduce bug

1. Have a desktop (Windows 11) and an Android device paired through Syncthing (Syncthing app on Android, SyncTrayzor 1.28.0 on Windows).
2. In List Modified settings, add "syncthing" as `Excluded names` in the `Criteria` section.
3. On Android, modify one of your note (here, it's `Workbench.md`).
4. `~syncthing~Workbench.md.tmp` will appear in the `LIST DELETED` log (see picture below).

![image](https://github.com/user-attachments/assets/50df199d-37f2-4cc8-8a26-57e8c8adc108)

### Additional information

Since I installed List Modified, many conflicts like what follows arise : 

![image](https://github.com/user-attachments/assets/d041b14e-de74-49bf-af82-047e32050183)

Three little modifications have been made to 3 notes, on Obsidian desktop, which led to that conflict. This is not easily reproducible, I tried twice more to make 3 little edits to 3 different notes, without any sync problem.

**Comment by technotherion** [comment]
Hello, I am also using "Excluded Names" with the new update and am also finding that my exclusions are still showing up. 

- Windows 10 / Debian Bookworm / Android
- Obsidian 1.7.5
- List Modified 3.2.1

Also related to syncing, I have a lot of conflicted files that get called "(xxx's conflicted copy)" etc. 
First, I deleted the entries from the deleted log that contained the word "conflicted". I then attempted to add "conflicted" to the excluded names and then pressed "force update the log note". The deleted files with "conflicted" in the title still reappear onto my deleted list.

**Comment by franciskafieh** [comment]
@Elaws is your original issue fixed with 3.2.1?

**Comment by Elaws** [comment]
@franciskafieh : Hi, the problem is still happening with 3.2.1.

Screenshot from today : 

![image](https://github.com/user-attachments/assets/59868bcc-b8e8-4b65-8486-1038539083b8)

**Comment by franciskafieh** [comment]
I will look into this sometime this week. Very busy with school right now

**Comment by franciskafieh** [comment]
Let me know if the new release fixes this issue. Thanks.

**Comment by Elaws** [comment]
I just made a modification of a note on my Android device, and checked the sync on my PC. Then I did the same from PC to Android.

For the first time, this did not write any "sync" files in the daily note log, and therefore didn't trigger many sync conflicts.

So, it seems to be a yes ! Thanks for investigating this issue. Will update if the fix happened to be unstable.

**Comment by franciskafieh** [comment]
Of course! Feel free to re-open if issue occurs again.
