### ISSUE TITLE
[BUG WITH WORKAROUND] Templater Folder Templates do not work with auto-create

### ISSUE THREAD

**Issue by franciskafieh** [franciskafieh/obsidian-list-modified#45]
## First Steps
- [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
- [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
- [x] I'm on the latest release of obsidian-list-modified
- [x] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug
When a note is automatically created, Templater's folder templates do not work

## Expected behaviour
They should work...

## Reproducing
N/A

## Workarounds
Need to try "daily note" template

**Comment by franciskafieh** [comment]
fixed?

**Comment by tophee** [comment]
I was just going to submit this as a feature request, but I'm glad to see that this is already supposed to work. 

> fixed?

No, it is not fixed. I have the templater plugin set to use a specific template when creating a new note in the "Daily" folder, but the plugin nevertheless creates its own note, by-passing the intended template.

**Comment by franciskafieh** [comment]
> I was just going to submit this as a feature request, but I'm glad to see that this is already supposed to work.

can you make sure "Trigger Templater on new file creation" setting is on inside of your Templater plugin settings (as per https://github.com/SilentVoid13/Templater/issues/919#issuecomment-1317950701)?

**Comment by tophee** [comment]
Yes, that is turned on. The template is applied when I create a new Daily note manually.

**Comment by franciskafieh** [comment]
In my local copy of 2.1 (not released as a binary yet--still being developed in a separate branch), the folder template is applied so long as the file is not written to by OLM. i.e. I can have the auto-create file setting on but not the auto-create heading setting on. Not sure exactly how to fix this atm, but I'll do some research

**Comment by franciskafieh** [comment]
seems to be an upstream bug related to a race condition between templater and other plugins: https://github.com/SilentVoid13/Templater/issues/924

note to self: the new .vault.process function *might* fix this?

**Comment by tophee** [comment]
This may be complete nonsense, since I don't know how the plugin works, but why don't you just turn off "auto-create heading"?  When I'm using a template, I neither assumed nor want the plugin to create its own heading but I made sure the template includes a heading that matches the one I specified in the plugin settings.

**Comment by franciskafieh** [comment]
> This may be complete nonsense, since I don't know how the plugin works, but why don't you just turn off "auto-create heading" when a template is active (or let the user do it)? When I'm using a template, I neither assumed nor want the plugin to create its own heading but I made sure the template includes a heading that matches the one I specified in the plugin settings.

That's a very reasonable idea. Maybe that will work for now until Templater finds a solution. I might make it a toggle mostly just so users understand what is going on

**Comment by franciskafieh** [comment]
Added a little description change here: https://github.com/franciskafieh/obsidian-list-modified/commit/60300c4f37eb05483035c5fb3833595dbcebf2fc
