### ISSUE TITLE
Heading reverts to default if not found in file

### ISSUE THREAD

**Issue by franciskafieh** [franciskafieh/obsidian-list-modified#55]
Maybe one more piece of feedback: I expected that if I change the "Heading" setting, when there is no appropriate section in the daily note, the "default" value will be created using my configuration. But I was wrong, and every time the plugin does not detect the specified Heading, it re-creates the default "(h1) Modified Today" and reverts my configuration back to the default value.

_Originally posted by @sotakal in https://github.com/franciskafieh/obsidian-list-modified/issues/54#issuecomment-1302349563_

**Comment by franciskafieh** [comment]
Going to work on getting this released for 2.1 (by October 13th for Obsidian October!) Just very busy atm

**Comment by franciskafieh** [comment]
Was not able to finish on time :(

Also realized that my current 2.0.2 pre-release is super buggy, so I'm not going to submit that either. I'm "finished" 2.1, but there remain a bunch of unexpected bugs I have to tackle, so it might take me a few for days to finish

**Comment by JoelAnderson-UU** [comment]
Hang in there!  This is a very, very handy plugin, and I'm really keen to use a stable version of 2.0!

**Comment by MMoMM-org** [comment]
to add to the issue.. the plugin is really spammy if this is the case.
I'm not able to create my daily note without it at least spamming 20 times that the header doesn't exists after starting Obsidian or switching over to Obsidian on the next date.
As I have to enter some information manually into my daily note I can't autocreate it.

**Comment by franciskafieh** [comment]
> to add to the issue.. the plugin is really spammy if this is the case. I'm not able to create my daily note without it at least spamming 20 times that the header doesn't exists after starting Obsidian or switching over to Obsidian on the next date. As I have to enter some information manually into my daily note I can't autocreate it.

Honestly, I think I'm just going to remove this notice or have it run once on startup.

**Comment by MMoMM-org** [comment]
I think you should wait some time after startup.. perhaps have an initial 5 minute wait? Also I have configured the write interval to 30.. so it really shouldn't spam that much.

**Comment by franciskafieh** [comment]
Yes, gotta fix that, too. I think it was fixed in 2.1 because I re-wrote the interval system, but now it's gone and I need to get to writing it again

**Comment by setu4993** [comment]
Still seeing this in v2.0.1 (current latest). Curious what the timeline on the fix / release for this is?

**Comment by franciskafieh** [comment]
2.0.2 should be latest, but that's irrelevant because it did not fix this issue. Honestly, I've just been busy with school and other projects. To add to that, I'm feeling demotivated because I was almost finished 2.1 (a big release that would've fixed this issue amongst others) and then it was wiped from my computer. Sorry for the delay to anyone waiting, but I promise I will get it done _eventually_.

**Comment by setu4993** [comment]
Thanks for that context, @franciskafieh. I totally understand how hard it is to start working on a project again after a data loss.

I'm not a NodeJS dev by any means, but I have dabbled a bit in TS. If you can point me in the approx direction for where to look to fix this, I can _try_ to help fix atleast this issue.

The rest of the v2.1 release sounds useful!

**Comment by franciskafieh** [comment]
Nah it's alright. Fixing this sole issue I could do pretty quick myself, but thanks for offering! If you'd like, I could release a minor fix just for this instead of waiting until 2.1 ---- On Thu, 29 Dec 2022 16:25:09 -0500  ***@***.***  wrote ----
Thanks for that context, @franciskafieh. I totally understand how hard it is to start working on a project again after a data loss.
I'm not a NodeJS dev by any means, but I have dabbled a bit in TS. If you can point me in the approx direction for where to look to fix this, I can try to help fix atleast this issue.
The rest of the v2.1 release sounds useful!

**Comment by setu4993** [comment]
I don't mind waiting for v2.1. Whichever way works best for you.

Thanks, @franciskafieh!

**Comment by franciskafieh** [comment]
Just got back from the mall, going to publish a super quick and dirty fix that should fix this issue temporarily until the re-write in 2.1

**Comment by franciskafieh** [comment]
[Release 2.0.3](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0.3) should fix the original bug. Please re-open if not.

**Comment by setu4993** [comment]
Wow, didn't expect this to be done so fast. Thanks a bunch, @franciskafieh!
